# Generated by Django 4.1.3 on 2023-01-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
